export const songs: { id: number; title: string }[] =  [
    { "id": 1, "title": "As It Was" },
    { "id": 2, "title": "Late Night Talking" },
    { "id": 3, "title": "Anti-Hero" },
    { "id": 4, "title": "Bejeweled" },
    { "id": 5, "title": "Lavender Haze" },
    { "id": 6, "title": "About Damn Time" },
    { "id": 7, "title": "2 Be Loved (Am I Ready)" },
    { "id": 8, "title": "Unholy" },
    { "id": 9, "title": "Gloria" },
    { "id": 10, "title": "I'm Not Here to Make Friends" },
    { "id": 11, "title": "Flowers" },
    { "id": 12, "title": "River" },
    { "id": 13, "title": "Jaded" },
    { "id": 14, "title": "N95" },
    { "id": 15, "title": "United in Grief" },
    { "id": 16, "title": "Silent Hill" },
    { "id": 17, "title": "Die Hard" },
    { "id": 18, "title": "Euphoria" },
    { "id": 19, "title": "Calm Down" },
    { "id": 20, "title": "Holiday" },
    { "id": 21, "title": "Finesse" },
    { "id": 22, "title": "Last Last" },
    { "id": 23, "title": "Kilometre" },
    { "id": 24, "title": "Wait for U" },
    { "id": 25, "title": "Puffin on Zootiez" },
    { "id": 26, "title": "Super Freaky Girl" },
    { "id": 27, "title": "Red Ruby Da Sleeze" },
    { "id": 28, "title": "Players" },
    { "id": 29, "title": "No More Parties" },
    { "id": 30, "title": "Creepin'" },
    { "id": 31, "title": "Metro Spider" },
    { "id": 32, "title": "Niagara Falls" },
    { "id": 33, "title": "Die for You (Remix)" },
    { "id": 34, "title": "Out of Time" },
    { "id": 35, "title": "Less Than Zero" },
    { "id": 36, "title": "Sacrifice" },
    { "id": 37, "title": "Take My Breath" },
    { "id": 38, "title": "Pink Venom" },
    { "id": 39, "title": "Shut Down" },
    { "id": 40, "title": "Ready For Love" },
    { "id": 41, "title": "ANTIFRAGILE" },
    { "id": 42, "title": "UNFORGIVEN" },
    { "id": 43, "title": "Eve, Psyche & The Bluebeard’s Wife" },
    { "id": 44, "title": "Ditto" },
    { "id": 45, "title": "OMG" },
    { "id": 46, "title": "Hype Boy" },
    { "id": 47, "title": "Attention" },
    { "id": 48, "title": "Seven" },
    { "id": 49, "title": "3D" },
    { "id": 50, "title": "Standing Next to You" },
    { "id": 51, "title": "Snooze" },
    { "id": 52, "title": "Kill Bill" },
    { "id": 53, "title": "Good Days" },
    { "id": 54, "title": "Shirt" },
    { "id": 55, "title": "Blind" },
    { "id": 56, "title": "Special" },
    { "id": 57, "title": "Karma" },
    { "id": 58, "title": "Mastermind" },
    { "id": 59, "title": "You're Losing Me" },
    { "id": 60, "title": "Cruel Summer (Re-Release)" },
    { "id": 61, "title": "Paint The Town Red" },
    { "id": 62, "title": "Agora Hills" },
    { "id": 63, "title": "Demons" },
    { "id": 64, "title": "Attention" },
    { "id": 65, "title": "WOMAN" },
    { "id": 66, "title": "Ghost in the Machine" },
    { "id": 67, "title": "Nobody Gets Me" },
    { "id": 68, "title": "Used" },
    { "id": 69, "title": "Too Many Nights" },
    { "id": 70, "title": "Spin Bout U" },
    { "id": 71, "title": "Rich Flex" },
    { "id": 72, "title": "Hours in Silence" },
    { "id": 73, "title": "Search & Rescue" },
    { "id": 74, "title": "Slime You Out" },
    { "id": 75, "title": "IDGAF" },
    { "id": 76, "title": "Dance The Night" },
    { "id": 77, "title": "Houdini" },
    { "id": 78, "title": "Training Season" },
    { "id": 79, "title": "Don’t Start Now (Live 2023)" },
    { "id": 80, "title": "What Was I Made For?" },
    { "id": 81, "title": "Therefore I Am" },
    { "id": 82, "title": "TV" },
    { "id": 83, "title": "Lunch" },
    { "id": 84, "title": "Birds of a Feather" },
    { "id": 85, "title": "L’Amour de Ma Vie" },
    { "id": 86, "title": "Espresso" },
    { "id": 87, "title": "Feather" },
    { "id": 88, "title": "Nonsense" },
    { "id": 89, "title": "because i liked a boy" },
    { "id": 90, "title": "Brutal" },
    { "id": 91, "title": "Vampire" },
    { "id": 92, "title": "Get Him Back!" },
    { "id": 93, "title": "Bad Idea Right?" },
    { "id": 94, "title": "All-American Bitch" },
    { "id": 95, "title": "Greedy" },
    { "id": 96, "title": "Yes, And?" },
    { "id": 97, "title": "We Can't Be Friends" },
    { "id": 98, "title": "The Boy Is Mine" },
    { "id": 99, "title": "Supernatural" },
    { "id": 100, "title": "One Of The Girls" },
    { "id": 101, "title": "Murder On The Dancefloor (Re-Release)" },
    { "id": 102, "title": "Honey (2023)" },
    { "id": 103, "title": "Princess Diana" },
    { "id": 104, "title": "Boy's a Liar Pt. 2" },
    { "id": 105, "title": "Barbie World" },
    { "id": 106, "title": "On the Street" },
    { "id": 107, "title": "Like Crazy" },
    { "id": 108, "title": "Set Me Free Pt.2" },
    { "id": 109, "title": "Flower" },
    { "id": 110, "title": "VIBE" },
    { "id": 111, "title": "Fast Car (Luke Combs)" },
    { "id": 112, "title": "Something in the Orange" },
    { "id": 113, "title": "Tennessee Orange" },
    { "id": 114, "title": "Need a Favor" },
    { "id": 115, "title": "Everything I Love" },
    { "id": 116, "title": "Californian Soil" },
    { "id": 117, "title": "Chaise Longue" },
    { "id": 118, "title": "Space Ghost Coast to Coast" },
    { "id": 119, "title": "The Summoning" },
    { "id": 120, "title": "Granite" },
    { "id": 121, "title": "Cupid (Twin Ver.)" },
    { "id": 122, "title": "Super Shy" },
    { "id": 123, "title": "ETA" },
    { "id": 124, "title": "Cool With You" },
    { "id": 125, "title": "Get Up" },
    { "id": 126, "title": "S-Class" },
    { "id": 127, "title": "LALALA" },
    { "id": 128, "title": "Maniac" },
    { "id": 129, "title": "Case 143" },
    { "id": 130, "title": "Fact Check" },
    { "id": 131, "title": "Super" },
    { "id": 132, "title": "Spicy" },
    { "id": 133, "title": "Armageddon" },
    { "id": 134, "title": "Drama" },
    { "id": 135, "title": "EASY" },
    { "id": 136, "title": "Shut Up My Moms Calling" },
    { "id": 137, "title": "Heat Waves (2022 resurgence)" },
    { "id": 138, "title": "abcdefu" },
    { "id": 139, "title": "House on Fire" },
    { "id": 140, "title": "Peru" },
    { "id": 141, "title": "Kiss Me More" },
    { "id": 142, "title": "Stay" },
    { "id": 143, "title": "The Loneliest" },
    { "id": 144, "title": "Honey (2024)" },
    { "id": 145, "title": "Wildflower" },
    { "id": 146, "title": "Eyes Closed" },
    { "id": 147, "title": "Heaven" },
    { "id": 148, "title": "Miracle" },
    { "id": 149, "title": "Chemical" },
    { "id": 150, "title": "Used To Be Young" }
  ]

export function songTitleRandomizer(): string {
  const randomIndex = Math.floor(Math.random() * songs.length);
  return songs[randomIndex].title;
}
