import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/lib/shared/components/QueryProvider";
import { AppNavbar } from "@/lib/features/navbar/app-navbar";
import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data, error } = await supabase.auth.getUser();
  return (
    <html lang="en">
      <body
        className={`${figtree.variable}  antialiased font-sans h-dvh flex flex-col`}
      >
        <QueryProvider>
          <AppNavbar
            isAuthenticated={!!data.user}
            userId={data.user?.id || ""}
          />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
